PKG := "hestia"
VERSION := `Rscript -e "cat(read.dcf('DESCRIPTION')[,'Version'])"`
TARBALL := PKG + "_" + VERSION + ".tar.gz"

default: format lint docs test

[unix]
[doc('Clean up auxiliary files and directories')]
clean:
        rm -rf *.tar.gz *.Rcheck .Rproj.user src/*.o src/*.gcno src/*.gcda src/*.so src/*.dll figure figures doc Meta vignettes/*.html vignettes/*.pdf

[doc('Ensure local NAMESPACE exists (bootstrapped if missing)')]
bootstrap-namespace:
        #!/usr/bin/env Rscript
        if (!file.exists("NAMESPACE")) {
          writeLines(c("# Generated by roxygen2: do not edit by hand", "useDynLib(hestia, .registration = TRUE)"), "NAMESPACE")
        }

[doc('Regenerate roxygen output: man/*.Rd, NAMESPACE, and R/globals.R (all untracked)')]
docs: bootstrap-namespace
        #!/usr/bin/env Rscript
        if (require(roxygen2)) roxygen2::roxygenise() else stop("missing 'roxygen2'")

[doc('Format R code using air')]
format:
        air format .

[doc('Check R code using air and lintr, and verify that Rcpp exports are up to date')]
lint: lintair lintr check-rcpp

[doc('Check that Rcpp export bindings in src/ are synchronized with Stan models')]
check-rcpp:
        #!/usr/bin/env bash
        set -euo pipefail
        Rscript -e "if (require(Rcpp)) Rcpp::compileAttributes() else stop(\"missing 'Rcpp'\")"
        if ! git diff --quiet src/RcppExports.cpp; then
                echo "Error: src/RcppExports.cpp is out of date. Run 'just docs' or 'Rcpp::compileAttributes()' and commit the changes." >&2
                git diff src/RcppExports.cpp
                exit 1
        fi

[doc('Check R code using air')]
lintair:
        air format . --check

[doc('Check R code using lintr')]
lintr: bootstrap-namespace
        #!/usr/bin/env Rscript
        if (require(lintr)) lintr::lint_package() else stop("missing 'lintr'")

[doc('Run unit tests using devtools')]
test: bootstrap-namespace
        #!/usr/bin/env Rscript 
        library(devtools)
        devtools::test()

[doc('Run unit tests using devtools, stopping on first failure')]
test-fast filter="": bootstrap-namespace
        #!/usr/bin/env Rscript
        library(devtools)
        filter_arg <- trimws("{{ filter }}")
        if (nzchar(filter_arg)) {
          devtools::test(filter = filter_arg, stop_on_failure = TRUE)
        } else {
          devtools::test(stop_on_failure = TRUE)
        }

[doc('Check test coverage using covr')]
coverage: bootstrap-namespace
        #!/usr/bin/env Rscript
        if (require(covr)) print(covr::package_coverage()) else stop("missing 'covr'")

[doc('Check spelling across documentation and vignettes using spelling')]
spell: bootstrap-namespace
        #!/usr/bin/env Rscript
        if (require(spelling)) spelling::spell_check_package() else stop("missing 'spelling'")

[doc('Install development version of hestia')]
install: bootstrap-namespace docs
        R CMD INSTALL .

[doc('Remove development version of hestia')]
remove:
        R CMD REMOVE {{ PKG }}

[doc('Build a tar.gz artifact')]
build: bootstrap-namespace docs
        R CMD build .

[doc('Check the built tar.gz artifact')]
check: build
        R CMD check {{ TARBALL }} --no-manual --no-tests

[doc('Check the built tar.gz artifact using CRAN settings')]
check-cran: build
        R CMD check {{ TARBALL }} --as-cran

[doc('Render vignettes to PDF and HTML locally')]
render: bootstrap-namespace
        #!/usr/bin/env Rscript
        if (!require(rmarkdown)) stop("missing 'rmarkdown'")
        if (require(devtools)) devtools::load_all(quiet = TRUE)
        files <- list.files("vignettes", pattern = "\\.Rmd$", full.names = TRUE)
        for (f in files) {
          message("Rendering ", f, " to HTML...")
          rmarkdown::render(f, output_format = "html_document", quiet = TRUE)
          message("Rendering ", f, " to PDF...")
          rmarkdown::render(f, output_format = "pdf_document", quiet = TRUE)
        }

[group('site')]
[doc('Fast build of pkgdown documentation site into docs/ (no package reinstallation)')]
site: bootstrap-namespace docs
        #!/usr/bin/env Rscript
        if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
        pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

[group('site')]
[doc('Alias for just site (fast documentation build)')]
site-quick: site

[group('site')]
[doc('Full build of pkgdown site with package reinstallation so vignettes see updated data/code')]
site-full: bootstrap-namespace docs install
        #!/usr/bin/env Rscript
        if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
        pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

[group('site')]
[doc('Preview pkgdown documentation on localhost; optionally specify a vignette/article item to re-render (e.g. just site-preview SIR)')]
site-preview item="" port="8000": bootstrap-namespace docs
        #!/usr/bin/env Rscript
        if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
        if (!requireNamespace("httpuv", quietly = TRUE)) stop("missing 'httpuv'")

        item <- trimws("{{ item }}")
        port_num <- as.integer("{{ port }}")
        url_path <- ""

        if (nzchar(item)) {
          clean_item <- tools::file_path_sans_ext(basename(item))

          if (identical(clean_item, "all")) {
            message("Re-building entire pkgdown site...")
            pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
          } else if (identical(clean_item, "reference")) {
            message("Re-building reference index and documentation...")
            pkgdown::build_reference()
            url_path <- "reference/index.html"
          } else if (clean_item %in% c("home", "index", "readme")) {
            message("Re-building home page...")
            pkgdown::build_home()
            url_path <- "index.html"
          } else {
            message(sprintf("Targeted build for article '%s'...", clean_item))
            pkgdown::build_article(clean_item)
            url_path <- sprintf("articles/%s.html", clean_item)
          }
        } else {
          message("Re-building entire pkgdown site...")
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        }

        target_url <- sprintf("http://127.0.0.1:%d/%s", port_num, url_path)
        message(sprintf("Serving pkgdown site at %s (Ctrl+C to stop)", target_url))
        httpuv::runStaticServer(
          dir = "docs",
          host = "127.0.0.1",
          port = port_num,
          browse = interactive() || nzchar(Sys.getenv("BROWSER"))
        )
