#' Simulated SIR household data
#'
#' Individual-level outcomes simulated from a basic
#' susceptible-infected-recovered (SIR) model for 500 households. Everyone
#' starts susceptible, the daily extra-household infection probability is 1%,
#' and the daily intra-household infection probability is 5%. Each individual
#' has two binary observations: one informative about active infection (e.g. a
#' PCR test) and one informative about recovery (e.g. an IgG antibody test).
#'
#' @format A data frame with one row per individual per day and the following
#'   columns:
#' \describe{
#'   \item{t}{Day of observation.}
#'   \item{part_id}{Participant identifier within the household.}
#'   \item{enroll}{Enrollment indicator (1 = enrolled, 0 = not enrolled).}
#'   \item{state}{True latent compartment (1 = S, 2 = I, 3 = R).}
#'   \item{hh_size}{Household size.}
#'   \item{hh_id}{Household identifier.}
#'   \item{pcr}{Binary outcome informative about active infection.}
#'   \item{igg}{Binary outcome informative about recovery.}
#' }
#' @source Generated by \code{data-raw/sir_data.R}.
"sir"

#' Fitted draws for the basic SIR model
#'
#' Posterior draws from \code{\link{run_model}} fit to the \code{\link{sir}}
#' data using a basic SIR infection process (fitting the recovery rate) and a
#' two-test observation process. Bundling the result lets the vignette display
#' model output without re-running the Stan model. Parameters are on the model's
#' internal scale (logit for probabilities and rates).
#'
#' @format A \code{posterior} \code{draws_array} with parameters
#'   \code{eh_prob}, \code{ih_prob}, and \code{gamma}.
#' @source Generated by \code{data-raw/sir_res.R}.
"sir_res"

#' Simulated SIR household data with covariates
#'
#' Individual-level outcomes simulated from a basic SIR model for 500
#' households, together with two binary individual-level covariates that affect
#' the intra- and extra-household infection probabilities. Used to demonstrate
#' fitting covariate effects.
#'
#' @format A list with two elements:
#' \describe{
#'   \item{observations}{A data frame of outcomes with the same columns as
#'     \code{\link{sir}}.}
#'   \item{covariates}{A data frame with one row per individual and two binary
#'     covariate columns, \code{x1} and \code{x2}.}
#' }
#' @source Generated by \code{data-raw/sir_cov_data.R}.
"sir_cov"

#' Fitted draws for the SIR model with covariates
#'
#' Posterior draws from \code{\link{run_model}} fit to \code{\link{sir_cov}}
#' with both intra- and extra-household covariates. Bundling the result lets the
#' vignette display model output without re-running the Stan model. Infection
#' probabilities and rates are on the logit scale and covariate coefficients are
#' on the log scale.
#'
#' @format A \code{posterior} \code{draws_array} with parameters
#'   \code{eh_prob}, \code{ih_prob}, \code{gamma}, \code{x1_eh}, \code{x2_eh},
#'   \code{x1_ih}, and \code{x2_ih}.
#' @source Generated by \code{data-raw/sir_cov_res.R}.
"sir_cov_res"

#' Simulated SIIR household data
#'
#' Individual-level outcomes simulated from an SIIR model for 500 households, in
#' which infection splits into symptomatic (\code{Is}) and asymptomatic
#' (\code{Ia}) compartments. The two infectious compartments have separate
#' intra-household infection probabilities. Each individual has three binary
#' observations: one informative about active infection (e.g. a PCR test), one
#' informative about recovery (e.g. an IgG antibody test), and one indicating
#' symptoms.
#'
#' @format A data frame with one row per individual per day and the following
#'   columns:
#' \describe{
#'   \item{t}{Day of observation.}
#'   \item{part_id}{Participant identifier within the household.}
#'   \item{enroll}{Enrollment indicator (1 = enrolled, 0 = not enrolled).}
#'   \item{state}{True latent compartment (1 = S, 2 = Is, 3 = Ia, 4 = R).}
#'   \item{hh_size}{Household size.}
#'   \item{hh_id}{Household identifier.}
#'   \item{pcr}{Binary outcome informative about active infection.}
#'   \item{igg}{Binary outcome informative about recovery.}
#'   \item{symp}{Binary outcome indicating symptoms.}
#' }
#' @source Generated by \code{data-raw/siir_data.R}.
"siir"

#' Fitted draws for the SIIR model
#'
#' Posterior draws from \code{\link{run_model}} fit to the \code{\link{siir}}
#' data using an infection process with separate symptomatic and asymptomatic
#' compartments. Bundling the result lets the vignette display model output
#' without re-running the Stan model. Parameters are on the model's internal
#' scale (logit for probabilities, rates, and the symptomatic split).
#'
#' @format A \code{posterior} \code{draws_array} with parameters
#'   \code{eh_prob}, \code{ih_prob_Is}, \code{ih_prob_Ia}, \code{gamma_s},
#'   \code{gamma_a}, and \code{phi}.
#' @source Generated by \code{data-raw/siir_res.R}.
"siir_res"
