# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "param", # <get_transmission_details>
  "hh_id", # <make_stan_data>
  "part_id", # <make_stan_data>
  "hh_size", # <make_stan_data>
  "row_id", # <make_stan_data>
  "trans_row", # <make_stan_data>
  "trans_col", # <make_stan_data>
  "mult_row", # <make_stan_data>
  "mult_col", # <make_stan_data>
  NULL
))
